# -*- coding: utf-8 -*-
"""label_recogntition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WtyIe12UacDvqvqJX6zQj6Cx5IoIHXfq
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#!pip install --upgrade azure-cognitiveservices-vision-computervision
#!pip install fuzzywuzzy python-levenshtein
from azure.cognitiveservices.vision.computervision import ComputerVisionClient
from azure.cognitiveservices.vision.computervision.models import OperationStatusCodes
from azure.cognitiveservices.vision.computervision.models import VisualFeatureTypes
from msrest.authentication import CognitiveServicesCredentials

from module_azure import Azure_recognition
from matching import make_json
from fuzzywuzzy import fuzz
# import difflib
# from difflib import SequenceMatcher
from array import array
import os
import json
import numpy as np
# from PIL import Image
import sys
import time
import pandas as pd

    
def main(algorithm, params):
    print(params)
    ingredient_data = get_from_db()
    recognition = algorithm.read_images(params = params)
    print(recognition)
    return make_json(ingredient_data, recognition)
    
   
def get_from_db():
    '''
    En el futuro aca se llama a la db con sqlalchemy
    '''
    return pd.read_csv('https://raw.githubusercontent.com/egonik-unlp/label_recognition/main/data_rubros/todos.csv')




### Para pruebas

if __name__ == '__main__':
    responses = []
    image_files = [file for file in os.listdir('test_images') if 'jpg' in file]
    for image in image_files:
        responses.append(main(Azure_recognition(), {
            'rubro': 'todos',
            'image_file': os.path.join('test_images',image) 
        }))
    with open('output.json', 'w') as file:
        json.dump(responses, file)
